/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinanceDashboardRouteImport } from './routes/finance.dashboard'
import { Route as FinanceReviewRouteImport } from './routes/finance.review'
import { Route as ProcurementDashboardRouteImport } from './routes/procurement.dashboard'
import { Route as VendorDashboardRouteImport } from './routes/vendor.dashboard'
import { Route as VendorOrgSearchRouteImport } from './routes/vendor.org-search'
import { Route as FinanceInvoicesIdRouteImport } from './routes/finance.invoices.$id'
import { Route as ProcurementInvoicesIndexRouteImport } from './routes/procurement.invoices.index'
import { Route as ProcurementInvoicesIdRouteImport } from './routes/procurement.invoices.$id'
import { Route as ProcurementInvoicesNewRouteImport } from './routes/procurement.invoices.new'
import { Route as VendorInvoiceNewRouteImport } from './routes/vendor.invoice.new'
import { Route as VendorInvoicesIndexRouteImport } from './routes/vendor.invoices.index'
import { Route as VendorInvoicesIdRouteImport } from './routes/vendor.invoices.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceDashboardRoute = FinanceDashboardRouteImport.update({
  id: '/finance/dashboard',
  path: '/finance/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceReviewRoute = FinanceReviewRouteImport.update({
  id: '/finance/review',
  path: '/finance/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementDashboardRoute = ProcurementDashboardRouteImport.update({
  id: '/procurement/dashboard',
  path: '/procurement/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/vendor/dashboard',
  path: '/vendor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorOrgSearchRoute = VendorOrgSearchRouteImport.update({
  id: '/vendor/org-search',
  path: '/vendor/org-search',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceInvoicesIdRoute = FinanceInvoicesIdRouteImport.update({
  id: '/finance/invoices/$id',
  path: '/finance/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementInvoicesIndexRoute =
  ProcurementInvoicesIndexRouteImport.update({
    id: '/procurement/invoices/',
    path: '/procurement/invoices/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProcurementInvoicesIdRoute = ProcurementInvoicesIdRouteImport.update({
  id: '/procurement/invoices/$id',
  path: '/procurement/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementInvoicesNewRoute = ProcurementInvoicesNewRouteImport.update({
  id: '/procurement/invoices/new',
  path: '/procurement/invoices/new',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorInvoiceNewRoute = VendorInvoiceNewRouteImport.update({
  id: '/vendor/invoice/new',
  path: '/vendor/invoice/new',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorInvoicesIndexRoute = VendorInvoicesIndexRouteImport.update({
  id: '/vendor/invoices/',
  path: '/vendor/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorInvoicesIdRoute = VendorInvoicesIdRouteImport.update({
  id: '/vendor/invoices/$id',
  path: '/vendor/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/finance/dashboard': typeof FinanceDashboardRoute
  '/finance/review': typeof FinanceReviewRoute
  '/procurement/dashboard': typeof ProcurementDashboardRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/org-search': typeof VendorOrgSearchRoute
  '/finance/invoices/$id': typeof FinanceInvoicesIdRoute
  '/procurement/invoices/$id': typeof ProcurementInvoicesIdRoute
  '/procurement/invoices/new': typeof ProcurementInvoicesNewRoute
  '/vendor/invoice/new': typeof VendorInvoiceNewRoute
  '/vendor/invoices/$id': typeof VendorInvoicesIdRoute
  '/procurement/invoices/': typeof ProcurementInvoicesIndexRoute
  '/vendor/invoices/': typeof VendorInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/finance/dashboard': typeof FinanceDashboardRoute
  '/finance/review': typeof FinanceReviewRoute
  '/procurement/dashboard': typeof ProcurementDashboardRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/org-search': typeof VendorOrgSearchRoute
  '/finance/invoices/$id': typeof FinanceInvoicesIdRoute
  '/procurement/invoices/$id': typeof ProcurementInvoicesIdRoute
  '/procurement/invoices/new': typeof ProcurementInvoicesNewRoute
  '/vendor/invoice/new': typeof VendorInvoiceNewRoute
  '/vendor/invoices/$id': typeof VendorInvoicesIdRoute
  '/procurement/invoices': typeof ProcurementInvoicesIndexRoute
  '/vendor/invoices': typeof VendorInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/finance/dashboard': typeof FinanceDashboardRoute
  '/finance/review': typeof FinanceReviewRoute
  '/procurement/dashboard': typeof ProcurementDashboardRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/org-search': typeof VendorOrgSearchRoute
  '/finance/invoices/$id': typeof FinanceInvoicesIdRoute
  '/procurement/invoices/$id': typeof ProcurementInvoicesIdRoute
  '/procurement/invoices/new': typeof ProcurementInvoicesNewRoute
  '/vendor/invoice/new': typeof VendorInvoiceNewRoute
  '/vendor/invoices/$id': typeof VendorInvoicesIdRoute
  '/procurement/invoices/': typeof ProcurementInvoicesIndexRoute
  '/vendor/invoices/': typeof VendorInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/finance/dashboard'
    | '/finance/review'
    | '/procurement/dashboard'
    | '/vendor/dashboard'
    | '/vendor/org-search'
    | '/finance/invoices/$id'
    | '/procurement/invoices/$id'
    | '/procurement/invoices/new'
    | '/vendor/invoice/new'
    | '/vendor/invoices/$id'
    | '/procurement/invoices/'
    | '/vendor/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/finance/dashboard'
    | '/finance/review'
    | '/procurement/dashboard'
    | '/vendor/dashboard'
    | '/vendor/org-search'
    | '/finance/invoices/$id'
    | '/procurement/invoices/$id'
    | '/procurement/invoices/new'
    | '/vendor/invoice/new'
    | '/vendor/invoices/$id'
    | '/procurement/invoices'
    | '/vendor/invoices'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/finance/dashboard'
    | '/finance/review'
    | '/procurement/dashboard'
    | '/vendor/dashboard'
    | '/vendor/org-search'
    | '/finance/invoices/$id'
    | '/procurement/invoices/$id'
    | '/procurement/invoices/new'
    | '/vendor/invoice/new'
    | '/vendor/invoices/$id'
    | '/procurement/invoices/'
    | '/vendor/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  FinanceDashboardRoute: typeof FinanceDashboardRoute
  FinanceReviewRoute: typeof FinanceReviewRoute
  ProcurementDashboardRoute: typeof ProcurementDashboardRoute
  VendorDashboardRoute: typeof VendorDashboardRoute
  VendorOrgSearchRoute: typeof VendorOrgSearchRoute
  FinanceInvoicesIdRoute: typeof FinanceInvoicesIdRoute
  ProcurementInvoicesIdRoute: typeof ProcurementInvoicesIdRoute
  ProcurementInvoicesNewRoute: typeof ProcurementInvoicesNewRoute
  VendorInvoiceNewRoute: typeof VendorInvoiceNewRoute
  VendorInvoicesIdRoute: typeof VendorInvoicesIdRoute
  ProcurementInvoicesIndexRoute: typeof ProcurementInvoicesIndexRoute
  VendorInvoicesIndexRoute: typeof VendorInvoicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/dashboard': {
      id: '/finance/dashboard'
      path: '/finance/dashboard'
      fullPath: '/finance/dashboard'
      preLoaderRoute: typeof FinanceDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/review': {
      id: '/finance/review'
      path: '/finance/review'
      fullPath: '/finance/review'
      preLoaderRoute: typeof FinanceReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/dashboard': {
      id: '/procurement/dashboard'
      path: '/procurement/dashboard'
      fullPath: '/procurement/dashboard'
      preLoaderRoute: typeof ProcurementDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/dashboard': {
      id: '/vendor/dashboard'
      path: '/vendor/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/org-search': {
      id: '/vendor/org-search'
      path: '/vendor/org-search'
      fullPath: '/vendor/org-search'
      preLoaderRoute: typeof VendorOrgSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/invoices/$id': {
      id: '/finance/invoices/$id'
      path: '/finance/invoices/$id'
      fullPath: '/finance/invoices/$id'
      preLoaderRoute: typeof FinanceInvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/invoices/': {
      id: '/procurement/invoices/'
      path: '/procurement/invoices'
      fullPath: '/procurement/invoices/'
      preLoaderRoute: typeof ProcurementInvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/invoices/$id': {
      id: '/procurement/invoices/$id'
      path: '/procurement/invoices/$id'
      fullPath: '/procurement/invoices/$id'
      preLoaderRoute: typeof ProcurementInvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/invoices/new': {
      id: '/procurement/invoices/new'
      path: '/procurement/invoices/new'
      fullPath: '/procurement/invoices/new'
      preLoaderRoute: typeof ProcurementInvoicesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/invoice/new': {
      id: '/vendor/invoice/new'
      path: '/vendor/invoice/new'
      fullPath: '/vendor/invoice/new'
      preLoaderRoute: typeof VendorInvoiceNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/invoices/': {
      id: '/vendor/invoices/'
      path: '/vendor/invoices'
      fullPath: '/vendor/invoices/'
      preLoaderRoute: typeof VendorInvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/invoices/$id': {
      id: '/vendor/invoices/$id'
      path: '/vendor/invoices/$id'
      fullPath: '/vendor/invoices/$id'
      preLoaderRoute: typeof VendorInvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  FinanceDashboardRoute: FinanceDashboardRoute,
  FinanceReviewRoute: FinanceReviewRoute,
  ProcurementDashboardRoute: ProcurementDashboardRoute,
  VendorDashboardRoute: VendorDashboardRoute,
  VendorOrgSearchRoute: VendorOrgSearchRoute,
  FinanceInvoicesIdRoute: FinanceInvoicesIdRoute,
  ProcurementInvoicesIdRoute: ProcurementInvoicesIdRoute,
  ProcurementInvoicesNewRoute: ProcurementInvoicesNewRoute,
  VendorInvoiceNewRoute: VendorInvoiceNewRoute,
  VendorInvoicesIdRoute: VendorInvoicesIdRoute,
  ProcurementInvoicesIndexRoute: ProcurementInvoicesIndexRoute,
  VendorInvoicesIndexRoute: VendorInvoicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
