/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FinanceDashboardRouteImport } from './routes/finance.dashboard'
import { Route as FinanceReviewRouteImport } from './routes/finance.review'
import { Route as ProcurementDashboardRouteImport } from './routes/procurement.dashboard'
import { Route as FinanceInvoicesIdRouteImport } from './routes/finance.invoices.$id'
import { Route as ProcurementInvoicesIndexRouteImport } from './routes/procurement.invoices.index'
import { Route as ProcurementInvoicesIdRouteImport } from './routes/procurement.invoices.$id'
import { Route as ProcurementInvoicesNewRouteImport } from './routes/procurement.invoices.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceDashboardRoute = FinanceDashboardRouteImport.update({
  id: '/finance/dashboard',
  path: '/finance/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceReviewRoute = FinanceReviewRouteImport.update({
  id: '/finance/review',
  path: '/finance/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementDashboardRoute = ProcurementDashboardRouteImport.update({
  id: '/procurement/dashboard',
  path: '/procurement/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceInvoicesIdRoute = FinanceInvoicesIdRouteImport.update({
  id: '/finance/invoices/$id',
  path: '/finance/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementInvoicesIndexRoute =
  ProcurementInvoicesIndexRouteImport.update({
    id: '/procurement/invoices/',
    path: '/procurement/invoices/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProcurementInvoicesIdRoute = ProcurementInvoicesIdRouteImport.update({
  id: '/procurement/invoices/$id',
  path: '/procurement/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementInvoicesNewRoute = ProcurementInvoicesNewRouteImport.update({
  id: '/procurement/invoices/new',
  path: '/procurement/invoices/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/finance/dashboard': typeof FinanceDashboardRoute
  '/finance/review': typeof FinanceReviewRoute
  '/procurement/dashboard': typeof ProcurementDashboardRoute
  '/finance/invoices/$id': typeof FinanceInvoicesIdRoute
  '/procurement/invoices/$id': typeof ProcurementInvoicesIdRoute
  '/procurement/invoices/new': typeof ProcurementInvoicesNewRoute
  '/procurement/invoices/': typeof ProcurementInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/finance/dashboard': typeof FinanceDashboardRoute
  '/finance/review': typeof FinanceReviewRoute
  '/procurement/dashboard': typeof ProcurementDashboardRoute
  '/finance/invoices/$id': typeof FinanceInvoicesIdRoute
  '/procurement/invoices/$id': typeof ProcurementInvoicesIdRoute
  '/procurement/invoices/new': typeof ProcurementInvoicesNewRoute
  '/procurement/invoices': typeof ProcurementInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/finance/dashboard': typeof FinanceDashboardRoute
  '/finance/review': typeof FinanceReviewRoute
  '/procurement/dashboard': typeof ProcurementDashboardRoute
  '/finance/invoices/$id': typeof FinanceInvoicesIdRoute
  '/procurement/invoices/$id': typeof ProcurementInvoicesIdRoute
  '/procurement/invoices/new': typeof ProcurementInvoicesNewRoute
  '/procurement/invoices/': typeof ProcurementInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/finance/dashboard'
    | '/finance/review'
    | '/procurement/dashboard'
    | '/finance/invoices/$id'
    | '/procurement/invoices/$id'
    | '/procurement/invoices/new'
    | '/procurement/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/finance/dashboard'
    | '/finance/review'
    | '/procurement/dashboard'
    | '/finance/invoices/$id'
    | '/procurement/invoices/$id'
    | '/procurement/invoices/new'
    | '/procurement/invoices'
  id:
    | '__root__'
    | '/'
    | '/finance/dashboard'
    | '/finance/review'
    | '/procurement/dashboard'
    | '/finance/invoices/$id'
    | '/procurement/invoices/$id'
    | '/procurement/invoices/new'
    | '/procurement/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinanceDashboardRoute: typeof FinanceDashboardRoute
  FinanceReviewRoute: typeof FinanceReviewRoute
  ProcurementDashboardRoute: typeof ProcurementDashboardRoute
  FinanceInvoicesIdRoute: typeof FinanceInvoicesIdRoute
  ProcurementInvoicesIdRoute: typeof ProcurementInvoicesIdRoute
  ProcurementInvoicesNewRoute: typeof ProcurementInvoicesNewRoute
  ProcurementInvoicesIndexRoute: typeof ProcurementInvoicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/dashboard': {
      id: '/finance/dashboard'
      path: '/finance/dashboard'
      fullPath: '/finance/dashboard'
      preLoaderRoute: typeof FinanceDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/review': {
      id: '/finance/review'
      path: '/finance/review'
      fullPath: '/finance/review'
      preLoaderRoute: typeof FinanceReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/dashboard': {
      id: '/procurement/dashboard'
      path: '/procurement/dashboard'
      fullPath: '/procurement/dashboard'
      preLoaderRoute: typeof ProcurementDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/invoices/$id': {
      id: '/finance/invoices/$id'
      path: '/finance/invoices/$id'
      fullPath: '/finance/invoices/$id'
      preLoaderRoute: typeof FinanceInvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/invoices/': {
      id: '/procurement/invoices/'
      path: '/procurement/invoices'
      fullPath: '/procurement/invoices/'
      preLoaderRoute: typeof ProcurementInvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/invoices/$id': {
      id: '/procurement/invoices/$id'
      path: '/procurement/invoices/$id'
      fullPath: '/procurement/invoices/$id'
      preLoaderRoute: typeof ProcurementInvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/invoices/new': {
      id: '/procurement/invoices/new'
      path: '/procurement/invoices/new'
      fullPath: '/procurement/invoices/new'
      preLoaderRoute: typeof ProcurementInvoicesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinanceDashboardRoute: FinanceDashboardRoute,
  FinanceReviewRoute: FinanceReviewRoute,
  ProcurementDashboardRoute: ProcurementDashboardRoute,
  FinanceInvoicesIdRoute: FinanceInvoicesIdRoute,
  ProcurementInvoicesIdRoute: ProcurementInvoicesIdRoute,
  ProcurementInvoicesNewRoute: ProcurementInvoicesNewRoute,
  ProcurementInvoicesIndexRoute: ProcurementInvoicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
